// const products = [
  
//   {
//     id: 1,
//     name: "ARAB MONEY",
//     description: "Luxurious and rich blend of precious woods and golden amber",
//     price: 49.99,
//     image: "src/Images/Arab-money.jpg",
//     rating: 4.9,
//     reviews: 89,
//     category: "Oriental",
//   },
//   {
//     id: 2,
//     name: "NIGHT ILLUSION",
//     description: "Deep and mysterious fragrance with dark, enchanting notes",
//     price: 49.99,
//     image: "src/Images/Night-Illusion.jpg",
//     rating: 4.8,
//     reviews: 124,
//     category: "Oriental",
//   },
//   {
//     id: 3,
//     name: "VELVET MUSK",
//     description: "Soft and musky with luxurious velvet undertones",
//     price: 49.99,
//     image: "src/Images/Velvet-Musk.jpg",
//     rating: 4.8,
//     reviews: 156,
//     category: "Oriental",
//   },
//   // Woody
//   {
//     id: 4,
//     name: "NIGHT IN PARIS",
//     description: "Romantic and elegant fragrance inspired by Parisian nights",
//     price: 49.99,
//     image: "src/Images/Night-in-Paris.jpg",
//     rating: 4.8,
//     reviews: 134,
//     category: "Woody",
//   },
//   {
//     id: 5,
//     name: "TROPICAL AROMA",
//     description: "Exotic and warm fragrance with tropical florals and spices",
//     price: 49.99,
//     image: "src/Images/Tropical-Aroma.jpg",
//     rating: 4.7,
//     reviews: 112,
//     category: "Woody",
//   },
//   // Fresh
//   {
//     id: 6,
//     name: "AQUA DI GIO",
//     description: "Refreshing aquatic scent that captures the essence of Mediterranean waters",
//     price: 49.99,
//     image: "src/Images/Aqua-Di-Gio.jpg",
//     rating: 4.8,
//     reviews: 156,
//     category: "Fresh",
//   },
//   {
//     id: 7,
//     name: "COOL WATER",
//     description: "Crisp and clean aquatic fragrance with invigorating freshness",
//     price: 49.99,
//     image: "src/Images/Cool-Water.jpg",
//     rating: 4.7,
//     reviews: 203,
//     category: "Fresh",
//   },
//   // Floral
//   {
//     id: 8,
//     name: "WARDIA",
//     description: "Rich, floral and opulent with precious rose and jasmine",
//     price: 49.99,
//     image: "src/Images/Wardia.jpg",
//     rating: 4.9,
//     reviews: 98,
//     category: "Floral",
//   },
//   {
//     id: 9,
//     name: "CANDY CRUSH",
//     description: "Sweet and vibrant fragrance bursting with playful energy",
//     price: 49.99,
//     image: "src/Images/Candy-Crush.jpg",
//     rating: 4.6,
//     reviews: 178,
//     category: "Floral",
//   },
//   {
//     id: 10,
//     name: "MARSHEMELLOW",
//     description: "Sweet and warm gourmand with comforting vanilla notes",
//     price: 49.99,
//     image: "src/Images/MarsHemellow.jpg",
//     rating: 4.7,
//     reviews: 145,
//     category: "Floral",
//   },
//   {
//     id: 11,
//     name: "FRUITELLA",
//     description: "Juicy and fruity explosion of tropical and citrus notes",
//     price: 49.99,
//     image: "src/Images/Fruitella.jpg",
//     rating: 4.5,
//     reviews: 167,
//     category: "Floral",
//   },
//   {
//     id: 12,
//     name: "MIDNIGHT ROSE",
//     description: "Elegant evening fragrance with deep rose and amber",
//     price: 49.99,
//     image: "src/Images/Img-1.jpg", // Using available images
//     rating: 4.8,
//     reviews: 142,
//     category: "Floral",
//   },
//   {
//     id: 13,
//     name: "OCEAN BREEZE",
//     description: "Fresh marine scent with citrus top notes",
//     price: 49.99,
//     image: "src/Images/Img-2.jpg", // Using available images
//     rating: 4.7,
//     reviews: 98,
//     category: "Fresh",
//   },
//   {
//     id: 14,
//     name: "GOLDEN SAND",
//     description: "Warm oriental blend with precious woods",
//     price: 49.99,
//     image: "src/Images/Img-3.jpg", // Using available images
//     rating: 4.9,
//     reviews: 156,
//     category: "Oriental",
//   },
// ]

// const getProductById = (id) => products.find(p => p.id === parseInt(id));

// module.exports = { products, getProductById };